import type { Metadata } from "next";
import { Inter, Aclonica } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/NavBar";

const inter = Inter({ subsets: ["latin"] });
const aclonica = Aclonica({ style: "normal", weight: "400", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Globe Quest App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
