import type { Metadata } from "next";
import { Inter, Sarina } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/NavBar";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Globe Quest App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className='flex flex-col h-screen'>
          <Navbar />
          <main className='pt-16 flex-grow'>
            {children}
          </main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
